== 一个 `WM_KEYDOWN` 消息被发往应用程序(Windows)

HID把键盘按下的事件传送给 `KBDHID.sys` 驱动，把HID的信号转换成一个扫描码(Scancode)，这里回车的扫描码是 `VK_RETURN(0x0d)`。 `KBDHID.sys` 驱动和 `KBDCLASS.sys` (键盘类驱动,keyboard class driver)进行交互，这个驱动负责安全地处理所有键盘和小键盘的输入事件。之后它又去调用 `Win32K.sys` ，在这之前有可能把消息传递给安装的第三方键盘过滤器。这些都是发生在内核模式。

`Win32K.sys` 通过 `GetForegroundWindow()` API函数找到当前哪个窗口是活跃的。这个API函数提供了当前浏览器的地址栏的句柄。Windows系统的"message pump"机制调用 `SendMessage(hWnd, WM_KEYDOWN, VK_RETURN, lParam)` 函数， `lParam` 是一个用来指示这个按键的更多信息的掩码，这些信息包括按键重复次数（这里是0），实际扫描码（可能依赖于OEM厂商，不过通常不会是 `VK_RETURN` ），功能键（alt, shift, ctrl）是否被按下（在这里没有），以及一些其他状态。

Windows的 `SendMessage` API直接将消息添加到特定窗口句柄 `hWnd` 的消息队列中，之后赋给 `hWnd` 的主要消息处理函数 `WindowProc` 将会被调用，用于处理队列中的消息。

当前活跃的句柄 `hWnd` 实际上是一个edit control控件，这种情况下，`WindowProc` 有一个用于处理 `WM_KEYDOWN` 消息的处理器，这段代码会查看 `SendMessage` 传入的第三个参数 `wParam` ，因为这个参数是 `VK_RETURN` ，于是它知道用户按下了回车键。


== 一个 `KeyDown` NSEvent被发往应用程序(Mac OS X)

中断信号引发了I/O Kit Kext键盘驱动的中断处理事件，驱动把信号翻译成键码值，然后传给OS X的 `WindowServer` 进程。然后， `WindowServer` 将这个事件通过Mach端口分发给合适的（活跃的，或者正在监听的）应用程序，这个信号会被放到应用程序的消息队列里。队列中的消息可以被拥有足够高权限的线程使用 `mach_ipc_dispatch` 函数读取到。这个过程通常是由 `NSApplication` 主事件循环产生并且处理的，通过 `NSEventType` 为 `KeyDown` 的 `NSEvent` 。

== Xorg 服务器监听键码值(GNU/Linux)

当使用图形化的 X Server 时，X Server 会按照特定的规则把键码值再一次映射，映射成扫描码。当这个映射过程完成之后， X Server 把这个按键字符发送给窗口管理器(DWM，metacity, i3等等)，窗口管理器再把字符发送给当前窗口。当前窗口使用有关图形API把文字打印在输入框内。
